# name: str
#     model_name: str
#     endpoints: default to null
#         - api_base: str
#           api_key: str
#           api_version: str optional (only for azure)
#     api_type: str
#     tokenizer: str optional (to optimize token limits)
#     parallel: int

gpt-3.5-turbo-0125:
    model_name: gpt-3.5-turbo-0125
    endpoints: null
    api_type: openai
    parallel: 8

gpt-4-0314:
    model_name: gpt-4-0314
    endpoints: null
    api_type: openai
    parallel: 8

gpt-4-1106-preview:
    model_name: gpt-4-1106-preview
    endpoints: null
    api_type: openai
    parallel: 8

gpt-4o-batch:
    model_name: gpt-4o-batch
    endpoints: 
         - api_base: EMPTY
           api_key: EMPTY
           api_version: 2024-07-01-preview
    api_type: azure_batched
    parallel: 20  # This should reflect the number of prompts per batch
    system_prompt: cluster_info

gpt-4o-batch_2:
    model_name: gpt-4o
    endpoints: 
         - api_base: EMPTY
           api_key: EMPTY
           api_version: 2024-02-01
    api_type: azure
    parallel: 8  # This should reflect the number of prompts per batch
    system_prompt: cluster_info

gpt-4o:
    model_name: gpt-4o
    endpoints: 
         - api_base: EMPTY
           api_key: EMPTY
           api_version: 2024-02-01
    api_type: azure
    parallel: 8
    system_prompt: cluster_info

gpt-4o-mini:
    model_name: gpt-4o-mini
    endpoints: null
    api_type: openai
    parallel: 20
    system_prompt: cluster_info

gpt-4o-2024-08-06:
    model_name: gpt-4o-2024-08-06
    endpoints: null
    api_type: openai
    parallel: 20
    system_prompt: cluster_info

gpt-4o_no_prompt:
    model_name: gpt-4o
    endpoints: 
         - api_base: EMPTY
           api_key: EMPTY
           api_version: 2024-02-01
    api_type: azure
    parallel: 20

llama3_8b:
    model_name: llama3_8b
    endpoints: 
        - api_base: http://localhost:8000/v1
          api_key: EMPTY
    api_type: openai
    parallel: 200
    system_prompt: cluster_info

llama3_8b_fp8:
    model_name: llama3_8b_fp8
    endpoints: 
        - api_base: http://localhost:8000/v1
          api_key: EMPTY
    api_type: openai
    parallel: 200
    system_prompt: cluster_info

llama3_1_70b:
    model_name: llama3_1_70b
    endpoints: 
        - api_base: http://localhost:8000/v1
          api_key: EMPTY
    api_type: openai
    parallel: 50
    system_prompt: cluster_info

llama3_70b:
    model_name: llama3_70b
    endpoints: 
        - api_base: http://localhost:8000/v1
          api_key: EMPTY
    api_type: openai
    system_prompt: cluster_info
    parallel: 50

llama3_1_70b_fp8:
    model_name: llama3_1_70b_fp8
    endpoints: 
        - api_base: http://localhost:8000/v1
          api_key: EMPTY
    api_type: openai
    parallel: 100
    system_prompt: cluster_info

llama3_70b_fp8:
    model_name: llama3_70b_fp8
    endpoints: 
        - api_base: http://localhost:8000/v1
          api_key: EMPTY
    api_type: openai
    system_prompt: cluster_info
    parallel: 100

llama3_1_70b_awq_int4:
    model_name: llama3_1_70b_awq_int4
    endpoints: 
        - api_base: http://localhost:8000/v1
          api_key: EMPTY
    api_type: openai
    parallel: 100
    system_prompt: cluster_info

llama3_70b_awq_int4:
    model_name: llama3_70b_awq_int4
    endpoints: 
        - api_base: http://localhost:8000/v1
          api_key: EMPTY
    api_type: openai
    system_prompt: cluster_info
    parallel: 100

llama3_1_8b:
    model_name: llama3_1_8b
    endpoints: 
        - api_base: http://localhost:8000/v1
          api_key: EMPTY
    api_type: openai
    parallel: 200
    system_prompt: cluster_info

llama3_1_8b_fp8:
    model_name: llama3_1_8b_fp8
    endpoints: 
        - api_base: http://localhost:8000/v1
          api_key: EMPTY
    api_type: openai
    parallel: 200
    system_prompt: cluster_info

llama3_1_8b_awq_int4:
    model_name: llama3_1_8b_awq_int4
    endpoints: 
        - api_base: http://localhost:8000/v1
          api_key: EMPTY
    api_type: openai
    parallel: 200
    system_prompt: cluster_info

llama3_1_405b:
    model_name: meta.llama3-1-405b-instruct-v1:0
    endpoints: 
        - aws_region: us-west-2
        #   api_key: EMPTY
        #   api_secret_key: EMPTY
    api_type: aws
    model_type: llama-3.1
    system_prompt: cluster_info
    parallel: 10

mistral_large_2:
    model_name: mistral.mistral-large-2407-v1:0
    endpoints: 
        - aws_region: us-west-2
        #   api_key: EMPTY
        #   api_secret_key: EMPTY
    api_type: aws
    model_type: mistral-large-2
    system_prompt: cluster_info
    parallel: 10