# name: str
#     model_name: str
#     endpoints: default to null
#         - api_base: str
#           api_key: str
#           api_version: str optional (only for azure)
#     api_type: str
#     tokenizer: str optional (to optimize token limits)
#     parallel: int

gpt-3.5-turbo-0125:
    model_name: gpt-3.5-turbo-0125
    endpoints: null
    api_type: openai
    parallel: 8

gpt-4-0314:
    model_name: gpt-4-0314
    endpoints: null
    api_type: openai
    parallel: 8

gpt-4-1106-preview:
    model_name: gpt-4-1106-preview
    endpoints: null
    api_type: openai
    parallel: 8

gpt-4o:
    model_name: gpt-4o
    endpoints: 
         - api_base: EMPTY
           api_key: EMPTY
           api_version: 2024-02-01
    api_type: azure
    parallel: 10
    system_prompt: cluster_info

gpt-4o-mini:
    model_name: gpt-4o-mini
    endpoints: null
    api_type: openai
    parallel: 20
    system_prompt: cluster_info

gpt-4o-2024-08-06:
    model_name: gpt-4o-2024-08-06
    endpoints: null
    api_type: openai
    parallel: 20
    system_prompt: cluster_info

gpt-4o_no_prompt:
    model_name: gpt-4o
    endpoints: 
         - api_base: EMPTY
           api_key: EMPTY
           api_version: 2024-02-01
    api_type: azure
    parallel: 20

orca_8B: 
    model_name: dwetzel/Llama-3-8B-Instruct_Orce_plus
    endpoints: 
        - api_base: http://localhost:8000/v1
          api_key: EMPTY
    api_type: openai
    parallel: 200

llama3_8b:
    model_name: llama3_8b
    endpoints: 
        - api_base: http://localhost:8000/v1
          api_key: EMPTY
    api_type: openai
    parallel: 200
    system_prompt: cluster_info

llama3_8b_fp8:
    model_name: llama3_8b_fp8
    endpoints: 
        - api_base: http://localhost:8000/v1
          api_key: EMPTY
    api_type: openai
    parallel: 200
    system_prompt: cluster_info

codestral-22B: 
    model_name: mistralai/Codestral-22B-v0.1
    endpoints: 
        - api_base: http://localhost:8000/v1
          api_key: EMPTY
    api_type: openai
    parallel: 200

llama3_1_70b:
    model_name: llama3_1_70b
    endpoints: 
        - api_base: http://localhost:8000/v1
          api_key: EMPTY
    api_type: openai
    parallel: 50
    system_prompt: cluster_info

llama3_70b_no_prompt:
    model_name: llama3_70b_no_prompt
    endpoints: 
        - api_base: http://localhost:8000/v1
          api_key: EMPTY
    api_type: openai
    parallel: 50

llama3_70b:
    model_name: llama3_70b
    endpoints: 
        - api_base: http://localhost:8000/v1
          api_key: EMPTY
    api_type: openai
    system_prompt: cluster_info
    parallel: 50

llama3_1_70b_no_prompt:
    model_name: llama3_1_70b_no_prompt
    endpoints: 
        - api_base: http://localhost:8000/v1
          api_key: EMPTY
    api_type: openai
    parallel: 50

llama3_1_70b_no_prompt_2:
    model_name: llama3_1_70b_no_prompt
    endpoints: 
        - api_base: http://localhost:8000/v1
          api_key: EMPTY
    api_type: openai
    parallel: 50

llama3_1_70b_fp8:
    model_name: llama3_1_70b_fp8
    endpoints: 
        - api_base: http://localhost:8000/v1
          api_key: EMPTY
    api_type: openai
    parallel: 100
    system_prompt: cluster_info

llama3_1_70b_fp8_no_prompt:
    model_name: llama3_1_70b_fp8_no_prompt
    endpoints: 
        - api_base: http://localhost:8000/v1
          api_key: EMPTY
    api_type: openai
    parallel: 100

llama3_70b_fp8_no_prompt:
    model_name: llama3_70b_fp8_no_prompt
    endpoints: 
        - api_base: http://localhost:8000/v1
          api_key: EMPTY
    api_type: openai
    parallel: 100

llama3_70b_fp8:
    model_name: llama3_70b_fp8
    endpoints: 
        - api_base: http://localhost:8000/v1
          api_key: EMPTY
    api_type: openai
    system_prompt: cluster_info
    parallel: 100

llama3_1_70b_fp8_1:
    model_name: llama3_1_70b_fp8_1
    endpoints: 
        - api_base: http://localhost:8000/v1
          api_key: EMPTY
    api_type: openai
    parallel: 25
    system_prompt: cluster_info

llama3_1_70b_fp8_2:
    model_name: llama3_1_70b_fp8_2
    endpoints: 
        - api_base: http://localhost:8000/v1
          api_key: EMPTY
    api_type: openai
    parallel: 35
    system_prompt: cluster_info

llama3_1_70b_awq_int4:
    model_name: llama3_1_70b_awq_int4
    endpoints: 
        - api_base: http://localhost:8000/v1
          api_key: EMPTY
    api_type: openai
    parallel: 100
    system_prompt: cluster_info

llama3_1_70b_awq_int4_no_prompt:
    model_name: llama3_1_70b_awq_int4_no_prompt
    endpoints: 
        - api_base: http://localhost:8000/v1
          api_key: EMPTY
    api_type: openai
    parallel: 100

llama3_70b_awq_int4_no_prompt:
    model_name: llama3_70b_awq_int4_no_prompt
    endpoints: 
        - api_base: http://localhost:8000/v1
          api_key: EMPTY
    api_type: openai
    parallel: 100

llama3_70b_awq_int4:
    model_name: llama3_70b_awq_int4
    endpoints: 
        - api_base: http://localhost:8000/v1
          api_key: EMPTY
    api_type: openai
    system_prompt: cluster_info
    parallel: 100

llama3_1_8b:
    model_name: llama3_1_8b
    endpoints: 
        - api_base: http://localhost:8000/v1
          api_key: EMPTY
    api_type: openai
    parallel: 200
    system_prompt: cluster_info

llama3_1_8b_no_prompt:
    model_name: llama3_1_8b
    endpoints: 
        - api_base: http://localhost:8000/v1
          api_key: EMPTY
    api_type: openai
    parallel: 200

llama3_1_8b_fp8:
    model_name: llama3_1_8b_fp8
    endpoints: 
        - api_base: http://localhost:8000/v1
          api_key: EMPTY
    api_type: openai
    parallel: 200
    system_prompt: cluster_info

llama3_1_8b_fp8_no_prompt:
    model_name: llama3_1_8b_fp8
    endpoints: 
        - api_base: http://localhost:8000/v1
          api_key: EMPTY
    api_type: openai
    parallel: 200

llama3_1_8b_awq_int4:
    model_name: llama3_1_8b_awq_int4
    endpoints: 
        - api_base: http://localhost:8000/v1
          api_key: EMPTY
    api_type: openai
    parallel: 200
    system_prompt: cluster_info

llama3_1_8b_awq_int4_no_prompt:
    model_name: llama3_1_8b_awq_int4
    endpoints: 
        - api_base: http://localhost:8000/v1
          api_key: EMPTY
    api_type: openai
    parallel: 200

llama3_1_405b:
    model_name: meta.llama3-1-405b-instruct-v1:0
    endpoints: 
        - api_key: EMPTY
          api_secret_key: EMPTY
          aws_region: us-west-2
    api_type: aws
    model_type: llama-3.1
    system_prompt: cluster_info
    parallel: 10

llama3_1_405b_no_prompt:
    model_name: meta.llama3-1-405b-instruct-v1:0
    endpoints: 
        - api_key: EMPTY
          api_secret_key: EMPTY
          aws_region: us-west-2
    api_type: aws
    model_type: llama-3.1
    parallel: 10

mistral_large_2:
    model_name: mistral.mistral-large-2407-v1:0
    endpoints: 
        - api_key: EMPTY
          api_secret_key: EMPTY
          aws_region: us-west-2
    api_type: aws
    model_type: mistral-large-2
    system_prompt: cluster_info
    parallel: 10

mistral_large_2_no_prompt:
    model_name: mistral.mistral-large-2407-v1:0
    endpoints: 
        - api_key: EMPTY
          api_secret_key: EMPTY
          aws_region: us-west-2
    api_type: aws
    model_type: mistral-large-2
    parallel: 10