llama3_1_70b_fp8_dyn_self_guided_run_1:
  api_type: openai
  endpoints:
  - api_base: http://localhost:8000/v1
    api_key: EMPTY
  model_name: llama3_1_70b_fp8_dyn_self
  parallel: 50
  system_prompt: "\n            You are a sophisticated AI-Expert there to help users\
    \ solve tasks in several domains efficiently and accurately.\n            Now\
    \ solve the following task from the domain \"YOLO Object Detection\".\n\n    \
    \        "
