# name: str
#     model_name: str
#     endpoints: default to null
#         - api_base: str
#           api_key: str
#           api_version: str optional (only for azure)
#     api_type: str
#     tokenizer: str optional (to optimize token limits)
#     parallel: int

gpt-3.5-turbo-0125:
    model_name: gpt-3.5-turbo-0125
    endpoints: null
    api_type: openai
    parallel: 8

gpt-4-0314:
    model_name: gpt-4-0314
    endpoints: null
    api_type: openai
    parallel: 8

gpt-4-1106-preview:
    model_name: gpt-4-1106-preview
    endpoints: null
    api_type: openai
    parallel: 8

orca_8B: 
    model_name: dwetzel/Llama-3-8B-Instruct_Orce_plus
    endpoints: 
        - api_base: http://0.0.0.0:8000
          api_key: null
    api_type: openai
    parallel: 50

llama_3_8B:
    model_name: meta-llama/Meta-Llama-3-8B-Instruct
    endpoints: 
        - api_base: http://0.0.0.0:8000
          api_key: null
    api_type: openai
    parallel: 50