# name: str
#     model_name: str
#     endpoints: default to null
#         - api_base: str
#           api_key: str
#           api_version: str optional (only for azure)
#     api_type: str
#     tokenizer: str optional (to optimize token limits)
#     parallel: int

gpt-3.5-turbo-0125:
    model_name: gpt-3.5-turbo-0125
    endpoints: null
    api_type: openai
    parallel: 8

gpt-4-0314:
    model_name: gpt-4-0314
    endpoints: null
    api_type: openai
    parallel: 8

gpt-4-1106-preview:
    model_name: gpt-4-1106-preview
    endpoints: null
    api_type: openai
    parallel: 8

gpt-4o:
    model_name: gpt-4o
    endpoints: 
         - api_base: EMPTY
           api_key: EMPTY
           api_version: 2024-02-01
    api_type: azure
    parallel: 15

orca_8B: 
    model_name: dwetzel/Llama-3-8B-Instruct_Orce_plus
    endpoints: 
        - api_base: http://localhost:8000/v1
          api_key: EMPTY
    api_type: openai
    parallel: 200

llama_3_8B:
    model_name: meta-llama/Meta-Llama-3-8B-Instruct
    endpoints: 
        - api_base: http://localhost:8000/v1
          api_key: EMPTY
    api_type: openai
    parallel: 200

codestral-22B: 
    model_name: mistralai/Codestral-22B-v0.1
    endpoints: 
        - api_base: http://localhost:8000/v1
          api_key: EMPTY
    api_type: openai
    parallel: 200