name: config of answer generation for arena-hard-v0.1

bench_name: arena-hard-v0.1
# mt-bench


temperature: 0.0
max_tokens: 2048
num_choices: 1

# a list of model to generate answers
model_list:
  - llama3_1_70b
#  - gpt-3.5-turbo-0125
#  - gpt-4o
#  - orca_8B
#  - llama_3_8B