name: config of answer generation for arena-hard-v0.1

bench_name: arena-hard-v0.1
# mt-bench


temperature: 0.0
max_tokens: 4096
num_choices: 1

# a list of model to generate answers
model_list:
  - gpt-4o-2024-08-06
  - gpt-4o-mini
  - gpt-4o